Param(
    [string]$romsDir = "roms",
    [string]$outputFile = "roms/roms-data.js"
)

$romFiles = Get-ChildItem -Path $romsDir -Filter "*.ch8" | Sort-Object Name

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Auto-generated by generate-roms.ps1")
[void]$sb.AppendLine("const ROMS_DATA = {")

foreach ($rom in $romFiles) {
    $bytes = [System.IO.File]::ReadAllBytes($rom.FullName)
    $b64 = [System.Convert]::ToBase64String($bytes)
    $name = $rom.Name -replace '\.ch8$', ''
    [void]$sb.AppendLine("  `"$($name.Replace('"', '\"'))`": `"$b64`",")
}

[void]$sb.AppendLine("};")

# Also generate a simple list of ROM names for the dropdown
[void]$sb.AppendLine("const ROMS_LIST = [")
foreach ($rom in $romFiles) {
    $name = $rom.Name -replace '\.ch8$', ''
    [void]$sb.AppendLine("  `"$($name.Replace('"', '\"'))`",")
}
[void]$sb.AppendLine("];")

Set-Content -Path $outputFile -Value $sb.ToString()
Write-Host "Generated $outputFile with $($romFiles.Count) ROMs"
